# Generated by Django 4.2 on 2023-04-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
