# Generated by Django 4.2 on 2023-05-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_company_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='portfolio',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
